default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: vincents_cheat_sheet_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: vincents_cheat_sheet_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: vincents_cheat_sheet_production
  username: <%= ENV['POSTGRES_USER_PRODUCTION'] %>
  password: <%= ENV['POSTGRES_PASSWORD_PRODUCTION'] %>
